import React, { useState, useEffect } from 'react';
import { Bot, RefreshCw, FileText, CheckCircle, ExternalLink, Calendar, Search } from 'lucide-react';
import { toast } from 'react-hot-toast';
import { C } from '../constants/theme.js';
import { api } from '../services/api.js';

export const FounderReportsView = () => {
  const [logs, setLogs] = useState([]);
  const [loading, setLoading] = useState(true);
  const [refreshTrigger, setRefreshTrigger] = useState(0);

  useEffect(() => {
    const fetchLogs = async () => {
      setLoading(true);
      try {
        const res = await api.getWorkflowLogs();
        // Filter only for WF06 - Founder Dashboard reports
        const founderReports = (res.logs || []).filter(log => log.workflow === 'WF06');
        setLogs(founderReports);
      } catch (err) {
        console.error('Failed to fetch founder reports', err);
        toast.error('Failed to load founder reports');
      } finally {
        setLoading(false);
      }
    };
    fetchLogs();
  }, [refreshTrigger]);

  const refreshLogs = () => {
    setRefreshTrigger(prev => prev + 1);
  };

  return (
    <div style={{ padding: '32px', maxWidth: 1200, margin: '0 auto', fontFamily: "'Inter', sans-serif" }}>
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '32px' }}>
        <div>
          <h1 style={{ margin: 0, fontSize: 32, fontWeight: 800, color: C.text, display: 'flex', alignItems: 'center', gap: 12 }}>
            <div style={{ padding: 10, background: 'rgba(99, 102, 241, 0.1)', borderRadius: 12, color: '#6366f1', display: 'flex' }}>
              <Bot size={24} />
            </div>
            AI Founder Reports
          </h1>
          <p style={{ margin: '8px 0 0 0', color: C.muted, fontSize: 15 }}>
            Automated daily executive summaries generated by your AI business analyst.
          </p>
        </div>
        
        <button 
          onClick={refreshLogs}
          disabled={loading}
          style={{ 
            display: 'flex', alignItems: 'center', gap: 8, padding: '10px 18px', 
            background: C.card, border: `1px solid ${C.border}`, borderRadius: 8, 
            color: C.text, fontWeight: 600, cursor: loading ? 'not-allowed' : 'pointer',
            transition: 'all 0.2s', opacity: loading ? 0.7 : 1
          }}
        >
          <RefreshCw size={16} className={loading ? 'spin' : ''} />
          Refresh History
        </button>
      </div>

      {/* Reports Feed */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
        {loading && logs.length === 0 ? (
          <div style={{ padding: '40px', textAlign: 'center', color: C.muted, background: C.card, borderRadius: 16, border: `1px solid ${C.border}` }}>
            <RefreshCw size={24} className="spin" style={{ marginBottom: 12 }} />
            <p>Loading AI reports...</p>
          </div>
        ) : logs.length === 0 ? (
          <div style={{ padding: '60px 40px', textAlign: 'center', background: C.card, borderRadius: 16, border: `1px dashed ${C.border}` }}>
            <div style={{ width: 64, height: 64, borderRadius: 32, background: 'rgba(99, 102, 241, 0.1)', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 20px auto' }}>
              <FileText size={32} color="#6366f1" />
            </div>
            <h3 style={{ fontSize: 18, color: C.text, fontWeight: 700, margin: '0 0 8px 0' }}>No Reports Yet</h3>
            <p style={{ color: C.muted, maxWidth: 400, margin: '0 auto' }}>Run the Founder Dashboard workflow (WF06) in n8n to generate your first automated AI business report!</p>
          </div>
        ) : (
          logs.map((log) => (
            <div key={log.id} style={{ 
              background: C.card, 
              borderRadius: 16, 
              border: `1px solid ${C.border}`,
              overflow: 'hidden',
              boxShadow: '0 4px 20px rgba(0,0,0,0.2)'
            }}>
              <div style={{ 
                padding: '16px 24px', 
                borderBottom: `1px solid ${C.border}`, 
                display: 'flex', 
                justifyContent: 'space-between',
                alignItems: 'center',
                background: 'rgba(255,255,255,0.02)'
              }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 6, color: C.green, fontSize: 13, fontWeight: 600, background: 'rgba(34,197,94,0.1)', padding: '4px 10px', borderRadius: 20 }}>
                    <CheckCircle size={14} /> Delivered via WhatsApp
                  </div>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: 8, color: C.muted, fontSize: 13, fontWeight: 500 }}>
                  <Calendar size={14} />
                  {new Date(log.created_at).toLocaleString(undefined, { 
                    weekday: 'short', month: 'short', day: 'numeric', 
                    hour: 'numeric', minute: '2-digit' 
                  })}
                </div>
              </div>
              
              <div style={{ padding: '24px' }}>
                <div style={{ whiteSpace: 'pre-wrap', color: C.text, fontSize: 15, lineHeight: 1.7, opacity: 0.9 }}>
                  {log.message}
                </div>
              </div>
            </div>
          ))
        )}
      </div>

    </div>
  );
};
