import React, { useState, useEffect } from 'react';
import { C } from '../constants/theme.js';
import { api } from '../services/api.js';
import { RefreshCw, User, Trash2, X, AlertTriangle } from 'lucide-react';
import toast from 'react-hot-toast';

export const SalesTasksView = () => {
  const [tasks, setTasks] = useState([]);
  const [loading, setLoading] = useState(true);
  const [deleteConfirmId, setDeleteConfirmId] = useState(null);
  const [isDeleting, setIsDeleting] = useState(false);
  const [currentPage, setCurrentPage] = useState(1);
  const tasksPerPage = 10;

  useEffect(() => {
    fetchTasks();
  }, []);

  const fetchTasks = async () => {
    setLoading(true);
    try {
      const res = await api.get('/sales-tasks');
      if (res.success) {
        setTasks(res.tasks || []);
      }
    } catch (err) {
      console.error('Error fetching tasks:', err);
      toast.error('Failed to refresh tasks');
    } finally {
      setLoading(false);
    }
  };

  const updateStatus = async (id, status) => {
    try {
      const res = await api.put(`/sales-tasks/${id}/status`, { status });
      if (res.success) {
        setTasks(tasks.map(t => t.id === id ? { ...t, status: res.task.status } : t));
        toast.success(`Task marked as ${status}`);
      }
    } catch (err) {
      console.error('Error updating status:', err);
      toast.error('Failed to update task status');
    }
  };

  const executeDeleteTask = async () => {
    if (!deleteConfirmId) return;
    setIsDeleting(true);
    try {
      const res = await api.delete(`/sales-tasks/${deleteConfirmId}`);
      if (res.success) {
        setTasks(tasks.filter(t => t.id !== deleteConfirmId));
        toast.success('Task deleted successfully');
        setDeleteConfirmId(null);
      }
    } catch (err) {
      console.error('Error deleting task:', err);
      toast.error('Failed to delete task');
    } finally {
      setIsDeleting(false);
    }
  };

  const getStatusStyles = (status) => {
    switch(status) {
      case 'completed': 
        return { bg: 'rgba(16, 185, 129, 0.1)', text: '#10b981', border: 'rgba(16, 185, 129, 0.2)' };
      case 'processing': 
        return { bg: 'rgba(59, 130, 246, 0.1)', text: '#3b82f6', border: 'rgba(59, 130, 246, 0.2)' };
      default: // pending
        return { bg: 'rgba(245, 158, 11, 0.1)', text: '#f59e0b', border: 'rgba(245, 158, 11, 0.2)' };
    }
  };

  const formatTaskType = (type) => {
    switch(type) {
      case 'hot_lead': return '🔥 Hot Lead';
      case 'call': return '📞 Scheduled Call';
      case 'followup': return '💬 Follow-up';
      case 'overdue': return '⚠️ Overdue Task';
      default: return type;
    }
  };

  return (
    <div className="p-mobile" style={{ padding: 26, overflowY: 'auto', height: '100%', background: C.bg, position: 'relative' }}>
      
      {/* Custom select css overrides */}
      <style>{`
        .task-status-select {
          appearance: none;
          -webkit-appearance: none;
          -moz-appearance: none;
          background-image: url("data:image/svg+xml;utf8,<svg fill='%2364748b' height='24' viewBox='0 0 24 24' width='24' xmlns='http://www.w3.org/2000/svg'><path d='M7 10l5 5 5-5z'/><path d='M0 0h24v24H0z' fill='none'/></svg>");
          background-repeat: no-repeat;
          background-position: right 6px center;
          background-size: 16px;
          padding-right: 22px !important;
        }
      `}</style>

      {/* --- HEADER CONTROLS --- */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 16, marginBottom: 26 }}>
        <div>
          <h1 style={{ fontFamily: "'Syne', sans-serif", fontSize: 22, fontWeight: 800, color: C.text, display: 'flex', alignItems: 'center', gap: 8 }}>
            Today's Digest
            <User size={18} color={C.accent} />
          </h1>
          <p style={{ color: C.muted, fontSize: 12, marginTop: 3 }}>
            Review and manage daily tasks generated by the Sales Reminder Engine
          </p>
        </div>

        <button
          onClick={fetchTasks}
          style={{
            background: C.surface,
            border: `1px solid ${C.border}`,
            color: C.text,
            padding: '9px 16px',
            borderRadius: 9,
            cursor: 'pointer',
            fontSize: 12,
            fontWeight: 600,
            display: 'flex',
            alignItems: 'center',
            gap: 6,
            transition: 'background 0.2s ease'
          }}
          onMouseEnter={e => e.currentTarget.style.background = C.border}
          onMouseLeave={e => e.currentTarget.style.background = C.surface}
        >
          <RefreshCw size={12} className={loading ? 'animate-spin' : ''} />
          Refresh Tasks
        </button>
      </div>

      {/* --- TASKS TABLE --- */}
      <div className="table-responsive" style={{ background: C.card, border: '1px solid ' + C.border, borderRadius: 14, overflow: 'hidden' }}>
        {loading && tasks.length === 0 ? (
          <div style={{ textAlign: 'center', padding: 48, color: C.muted }}>Loading your tasks...</div>
        ) : tasks.length === 0 ? (
          <div style={{ textAlign: 'center', padding: 48, color: C.muted, display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12 }}>
            <User size={36} color={C.border} />
            <span style={{ fontSize: 13 }}>No tasks assigned for today. You're all caught up!</span>
          </div>
        ) : (
          <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
            <thead>
              <tr style={{ borderBottom: '1px solid ' + C.border }}>
                {['Lead', 'Contact Info', 'Task Type', 'Status Action'].map((h) => (
                  <th key={h} style={{ padding: '12px 16px', fontSize: 10, color: C.muted, fontWeight: 700, textTransform: 'uppercase', letterSpacing: 0.8 }}>
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {(() => {
                const indexOfLastTask = currentPage * tasksPerPage;
                const indexOfFirstTask = indexOfLastTask - tasksPerPage;
                const currentTasks = tasks.slice(indexOfFirstTask, indexOfLastTask);
                return currentTasks.map((task, idx) => {
                  const styles = getStatusStyles(task.status);
                  return (
                    <tr 
                      key={task.id} 
                    style={{ 
                      borderBottom: '1px solid ' + C.border, 
                      background: idx % 2 === 0 ? 'transparent' : 'rgba(255,255,255,0.01)' 
                    }}
                  >
                    {/* Lead Detail */}
                    <td style={{ padding: '14px 16px' }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                        <div style={{
                          width: 30, height: 30, borderRadius: '50%',
                          background: `${C.accent}15`, display: 'flex',
                          alignItems: 'center', justifyContent: 'center',
                          fontSize: 11, fontWeight: 700, color: C.accent, flexShrink: 0
                        }}>
                          {task.name ? task.name[0].toUpperCase() : 'L'}
                        </div>
                        <div>
                          <p style={{ fontSize: 13, fontWeight: 600, color: C.text }}>{task.name || 'Unknown Lead'}</p>
                          <span style={{ fontSize: 10, color: C.muted, textTransform: 'capitalize' }}>
                            Stage: {task.lead_status || 'New'}
                          </span>
                        </div>
                      </div>
                    </td>

                    {/* Contact Info */}
                    <td style={{ padding: '14px 16px' }}>
                      <p style={{ fontSize: 12, fontWeight: 500, color: C.text }}>{task.phone || '-'}</p>
                      <p style={{ fontSize: 10, color: C.muted }}>{task.email || 'No Email'}</p>
                    </td>

                    {/* Task Type */}
                    <td style={{ padding: '14px 16px' }}>
                      <span style={{ 
                        fontSize: 11, 
                        fontWeight: 600,
                        color: task.task_type === 'hot_lead' ? C.red : task.task_type === 'call' ? C.blue : C.purple, 
                        background: task.task_type === 'hot_lead' ? 'rgba(239, 68, 68, 0.1)' : task.task_type === 'call' ? 'rgba(59, 130, 246, 0.1)' : 'rgba(139, 92, 246, 0.1)', 
                        padding: '4px 10px', 
                        borderRadius: 12 
                      }}>
                        {formatTaskType(task.task_type)}
                      </span>
                    </td>

                    {/* Status Action & Delete */}
                    <td style={{ padding: '14px 16px' }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                        <select 
                          value={task.status}
                          onChange={(e) => updateStatus(task.id, e.target.value)}
                          className="task-status-select"
                          style={{
                            backgroundColor: styles.bg,
                            color: styles.text,
                            border: '1px solid ' + styles.border,
                            borderRadius: 14,
                            padding: '4px 10px',
                            fontSize: 11,
                            fontWeight: 700,
                            outline: 'none',
                            cursor: 'pointer',
                            transition: 'all 0.2s ease',
                          }}
                        >
                          <option value="pending" style={{ background: C.card, color: '#f59e0b' }}>Pending</option>
                          <option value="processing" style={{ background: C.card, color: '#3b82f6' }}>Processing</option>
                          <option value="completed" style={{ background: C.card, color: '#10b981' }}>Completed</option>
                        </select>
                        <button
                          onClick={() => setDeleteConfirmId(task.id)}
                          style={{
                            background: 'transparent',
                            border: 'none',
                            color: C.muted,
                            cursor: 'pointer',
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center',
                            padding: '4px',
                            borderRadius: '4px',
                            transition: 'color 0.2s ease'
                          }}
                          onMouseEnter={e => e.currentTarget.style.color = C.red}
                          onMouseLeave={e => e.currentTarget.style.color = C.muted}
                          title="Delete Task"
                        >
                          <Trash2 size={16} />
                        </button>
                      </div>
                    </td>
                  </tr>
                  );
                });
              })()}
            </tbody>
          </table>
        )}

        {/* Pagination Controls */}
        {tasks.length > tasksPerPage && (
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '14px 20px', background: C.card, borderTop: '1px solid ' + C.border }}>
            <span style={{ fontSize: 13, color: C.muted, fontWeight: 500 }}>
              Showing {((currentPage - 1) * tasksPerPage) + 1} to {Math.min(currentPage * tasksPerPage, tasks.length)} of {tasks.length} entries
            </span>
            <div style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
              <button 
                disabled={currentPage === 1}
                onClick={() => setCurrentPage(p => Math.max(1, p - 1))}
                style={{ padding: '6px 14px', background: 'transparent', border: '1px solid ' + C.border, borderRadius: 6, color: currentPage === 1 ? C.muted : C.text, cursor: currentPage === 1 ? 'not-allowed' : 'pointer', opacity: currentPage === 1 ? 0.5 : 1, fontSize: 13, fontWeight: 500, transition: 'all 0.2s' }}
              >
                Previous
              </button>
              <span style={{ fontSize: 13, color: C.text, fontWeight: 600 }}>
                Page {currentPage} of {Math.ceil(tasks.length / tasksPerPage)}
              </span>
              <button 
                disabled={currentPage === Math.ceil(tasks.length / tasksPerPage)}
                onClick={() => setCurrentPage(p => Math.min(Math.ceil(tasks.length / tasksPerPage), p + 1))}
                style={{ padding: '6px 14px', background: 'transparent', border: '1px solid ' + C.border, borderRadius: 6, color: currentPage === Math.ceil(tasks.length / tasksPerPage) ? C.muted : C.text, cursor: currentPage === Math.ceil(tasks.length / tasksPerPage) ? 'not-allowed' : 'pointer', opacity: currentPage === Math.ceil(tasks.length / tasksPerPage) ? 0.5 : 1, fontSize: 13, fontWeight: 500, transition: 'all 0.2s' }}
              >
                Next
              </button>
            </div>
          </div>
        )}
      </div>

      {/* Delete Confirmation Modal */}
      {deleteConfirmId && (
        <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.6)', backdropFilter: 'blur(4px)', zIndex: 1000, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 20 }}>
          <div style={{ background: C.surface, border: '1px solid ' + C.border, borderRadius: 12, width: '100%', maxWidth: 400, boxShadow: '0 20px 40px rgba(0,0,0,0.5)', overflow: 'hidden' }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '16px 20px', borderBottom: '1px solid ' + C.border, background: C.card }}>
              <h3 style={{ fontSize: 14, fontWeight: 700, color: C.text, display: 'flex', alignItems: 'center', gap: 8 }}>
                <AlertTriangle size={16} color={C.red} />
                Delete Task
              </h3>
              <button onClick={() => setDeleteConfirmId(null)} style={{ background: 'transparent', border: 'none', cursor: 'pointer', color: C.muted }}>
                <X size={16} />
              </button>
            </div>
            <div style={{ padding: '24px 20px', color: C.muted, fontSize: 13, lineHeight: 1.5 }}>
              Are you sure you want to permanently delete this task? This action cannot be undone and will remove the task history.
            </div>
            <div style={{ padding: '16px 20px', background: C.card, borderTop: '1px solid ' + C.border, display: 'flex', justifyContent: 'flex-end', gap: 12 }}>
              <button 
                onClick={() => setDeleteConfirmId(null)}
                style={{ background: 'transparent', border: '1px solid ' + C.border, color: C.text, padding: '8px 16px', borderRadius: 8, fontSize: 12, fontWeight: 600, cursor: 'pointer' }}
              >
                Cancel
              </button>
              <button 
                onClick={executeDeleteTask}
                disabled={isDeleting}
                style={{ background: C.red, border: 'none', color: '#fff', padding: '8px 16px', borderRadius: 8, fontSize: 12, fontWeight: 600, cursor: isDeleting ? 'not-allowed' : 'pointer', opacity: isDeleting ? 0.7 : 1 }}
              >
                {isDeleting ? 'Deleting...' : 'Delete Task'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
